### PR TITLE
Evolve pokemons after сatching

### PR DESCRIPTION
**Pull request by TheBringerOfPain**

### CODE REVIEW

**Comment by PocketMobsters** [comment]
Are you sure about this though? Don't people use the current evolve option to evolve on startup after using a lucky egg?

**Comment by navidemad** [comment]
:-1:

**Comment by TheBringerOfPain** [comment]
Yes, you are right. Just i don't have any lacky eggs and need an option like this.

**Comment by Sylencer90** [comment]
I mean it can be added by the creator for sure, but hopefully default as false.

**Comment by solenrus** [comment]
I do this manually with every update, this really needs to be an option in the settings.

**Comment by Shroomzie** [comment]
@solenrus i cant seem to find the code you have pushed to this project for this.

**Pull request closed without merging**
