### PR TITLE
Added PokemonInfo to API for BaseStats,Level,MaxCP,Perfection. Fixed proto for cpMultipliers(int->float)

### PR DESCRIPTION
**Pull request by 5andr0**
The CalculatePokemonPerfection function now calculates the perfect MaxCP
percentage based on BaseStats. I also had to fix the protocol to change
the cpMulitplier values from int to float values

### CODE REVIEW

**Comment by AdnanCukur** [comment]
what was wrong with the way it calculated perfection earlier ?

**Comment by UgaBugaBoo** [comment]
What's the difference between the two commits ?

**Comment by 5andr0** [comment]
First some background info: [TheSilphRoad Pokemon CP formula](https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/)
`Max CP = 0.1* ((BaseAtk + IV) * (BaseDef + IV)^0.5 * (BaseSta + IV)^0.5 * (CpM+ACpM)^2)`
As you can see the AttackIndividualValue has a greater impact on the CP than def/sta. The CP will also increase more with pokemons having high attack values. It'll be less for Pokemons whos CP is based on a high def base value. That's why we have to take the base stats into consideration. The previous function was just a little bit off, now its 100% accurate!

**Comment by OverlordQ** [comment]
You'll need to compile the proto file to generate a new Payloads.cs, otherwise it'll have no effect.

**Comment by tensei** [comment]
he changed the payload.cs if you would look at the changes 
and ofc it's tested and works

**Comment by navidemad** [comment]
Your payload changes crashed my appm invalid cast

**Pull request merged**
