### PR TITLE
Update ConfigPokemonsToKeep.txt

### PR DESCRIPTION
**Pull request by deknarf**
* Added rare and ultra rare Pokemon
* In appropriate PokeDex order (first>last)
* Fixed typo: Alahkazam (should be Alakazam)

### CODE REVIEW

**Comment by solenrus** [comment]
this shouldn't work cause of differences in allenums, not sure

**Comment by ThomasSRL** [comment]
Wasn't this just updated by @solenrus ?

**Comment by solenrus** [comment]
also Blastiose is misspelled,
@thomasSRL unfortunately had to revert, cause I was too slow on all the pulls.

**Comment by ThomasSRL** [comment]
@solenrus 
Are there any missing ones according to you? Perhaps you can create a new pull?

I'm still hoping for the radius patch to get re-opened. Don't want to start in central park to end up in Tokyo...

**Pull request merged**
