### PR TITLE
[FEATURE]: Player will now stay within a defined radius

### PR DESCRIPTION
**Pull request by Daylend**
I'm new to GIT, but I spent some time working on this. Feel free to mess with the formatting or whatever.

Added new setting "MaxTravelDistanceInMeters". 0 = infinite.

### CODE REVIEW

**Comment by TheCrimsonDevil** [comment]
Yes please! This would be a very welcome feature :+1:

**Comment by vcafezinho** [comment]
Perfect, this will be really good.

**Comment by ellm62** [comment]
A much needed feature to farm nests.

**Comment by ThomasSRL** [comment]
Nice work, but it does seem to crash for me, unlike the current live version. I'll try and post an error log soon!

**Comment by NecronomiconCoding** [comment]
fix  conflicts pls

**Comment by ThomasSRL** [comment]
There was no conflict when he released I think. I was able to compile and run.

**Pull request closed without merging**
