### PR TITLE
Catch while walking

### PR DESCRIPTION
**Pull request by Ehnoah**
Hope this is correct now

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
getting a build error , check please

**Comment by Meeplez** [comment]
you should make this a setting. i actually enjoy the time i spend in vr ^_^

**Comment by MonsterMMORPG** [comment]
i have just merged this with my repo :D

**Comment by MonsterMMORPG** [comment]
this seems like doing nothing? i cant find function your function anyhwere

shouldn't you call ExecuteFarmingPokestopsAndPokemons?

**Comment by ReddoKiddo** [comment]
Yea the whole function is missing

where is:
`functionExecutedWhileWalking`

**Comment by NecronomiconCoding** [comment]
not complete

**Pull request closed without merging**
